<a href="https://colab.research.google.com/github/kurofuku9000/SD_CollabTestV1.0/blob/main/DanbooruDataset_TorchCollab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test


In [ ]:
# @title Just a Test {"vertical-output":true,"display-mode":"form"}
import os
import numpy as np
import torch

print("Basic Workings Reminder")

tensor_A = torch.rand(3,4)
print(f"Shape of tensor: {tensor_A.shape}")
print(tensor_A)
tensor_B = torch.rand(4,5)


if torch.cuda.is_available():
  tensor_A.to("cuda")
  tensor_B.to("cuda")

T1 = tensor_A.T
print(T1)

T2 = torch.matmul(tensor_A,tensor_B)
print(T2)

agg = T2.sum()
print(type(agg))
print(agg)

agg_nm = agg.item()
print(type(agg_nm))
print(agg_nm)

Basic Workings Reminder
Shape of tensor: torch.Size([3, 4])
tensor([[0.5746, 0.6717, 0.8489, 0.1618],
        [0.6634, 0.5509, 0.6663, 0.2940],
        [0.6491, 0.1267, 0.1059, 0.8406]])
tensor([[0.5746, 0.6634, 0.6491],
        [0.6717, 0.5509, 0.1267],
        [0.8489, 0.6663, 0.1059],
        [0.1618, 0.2940, 0.8406]])
tensor([[1.2315, 1.2298, 0.6406, 1.4484, 1.2135],
        [1.2607, 1.1349, 0.7186, 1.2581, 1.0482],
        [1.2803, 0.9217, 0.9467, 0.6276, 0.4178]])
<class 'torch.Tensor'>
tensor(15.3784)
<class 'float'>
15.37840747833252


# Custom Database Loader
[Danbooru Aesthetics](https://huggingface.co/datasets/Majen/danbooru-aesthetic/tree/main)

